# Generated by Django 5.2.5 on 2025-08-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0002_aprendizcurso_curso_aprendizcurso_curso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aprendiz',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Aprendiz', 'verbose_name_plural': 'Aprendices'},
        ),
        migrations.RemoveField(
            model_name='aprendiz',
            name='programa',
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='ciudad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='correo',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='documento_identidad',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='telefono',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
