# Generated by Django 5.2.5 on 2025-08-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="programa",
            options={},
        ),
        migrations.RemoveField(
            model_name="programa",
            name="competencias",
        ),
        migrations.RemoveField(
            model_name="programa",
            name="duracion_meses",
        ),
        migrations.RemoveField(
            model_name="programa",
            name="fecha_creacion",
        ),
        migrations.RemoveField(
            model_name="programa",
            name="modalidad",
        ),
        migrations.RemoveField(
            model_name="programa",
            name="perfil_egreso",
        ),
        migrations.RemoveField(
            model_name="programa",
            name="regional",
        ),
        migrations.RemoveField(
            model_name="programa",
            name="requisitos_ingreso",
        ),
        migrations.AddField(
            model_name="programa",
            name="area_formacion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="programa",
            name="fecha_fin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="programa",
            name="fecha_inicio",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="programa",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="programa",
            name="centro_formacion",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="programa",
            name="codigo",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="programa",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="programa",
            name="duracion_horas",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="programa",
            name="estado",
            field=models.CharField(
                choices=[("ACT", "Activo"), ("INA", "Inactivo"), ("SUS", "Suspendido")],
                default="ACT",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="programa",
            name="fecha_registro",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="programa",
            name="nivel_formacion",
            field=models.CharField(
                choices=[
                    ("TEC", "Técnico"),
                    ("TGL", "Tecnólogo"),
                    ("ESP", "Especialización"),
                    ("PRE", "Pregrado"),
                    ("MAE", "Maestría"),
                    ("DOC", "Doctorado"),
                ],
                default="TEC",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="programa",
            name="nombre",
            field=models.CharField(max_length=200),
        ),
    ]
